"""Generate an HTML comparison report for H(AI)LP vs Baseline GPT.

Run:

    uv run python demo/generate_report.py

This will:
  - Run lightweight memory and speed benchmarks
  - Optionally sample quality metrics (random-init)
  - Produce `comparison_report.html` with inline PNG charts
"""

from __future__ import annotations

import argparse
import base64
import io
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import matplotlib.pyplot as plt

from benchmarks.memory_profile import benchmark_memory_vs_sequence_length
from benchmarks.quality_eval import benchmark_quality
from benchmarks.speed_profile import benchmark_speed_vs_sequence_length
from models.baseline_gpt import BaselineConfig, BaselineGPT
from models.hailp_model import HAILPConfig, HAILPModel
from training.device import DEVICE as DEFAULT_DEVICE
from training.device import DEVICE_NAME


def _fig_to_base64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("ascii")


def generate_report_html(mem_img: str, speed_img: str, quality_img: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>H(AI)LP Architecture Report</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 2rem; color: #111; }}
    h1, h2 {{ color: #222; }}
    .chart {{ margin-bottom: 3rem; }}
    img {{ max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; }}
    .summary {{ padding: 1rem; background: #f5f5f5; border-radius: 4px; margin-bottom: 2rem; }}
    code {{ background: #f0f0f0; padding: 0.1rem 0.25rem; border-radius: 3px; }}
  </style>
</head>
<body>
  <h1>H(AI)LP Architecture Report</h1>
  <div class="summary">
    <p>This report evaluates the H(AI)LP RWKV model (12-layer recurrent, fixed state)
    on memory usage, speed, and quality metrics. Optional Baseline GPT comparisons
    can be enabled with `--baseline`.</p>
  </div>

  <div class="chart">
    <h2>Memory vs Sequence Length</h2>
    <p>Baseline GPT RAM rises sharply with context length; H(AI)LP stays nearly flat
    thanks to a fixed-size recurrent state.</p>
    <img src="data:image/png;base64,{mem_img}" alt="Memory vs sequence length" />
  </div>

  <div class="chart">
    <h2>Speed vs Sequence Length (tokens/sec)</h2>
    <p>Forward speed for both models at different sequence lengths on this machine.
    At short contexts the transformer is fast; at long contexts H(AI)LP's O(n)
    time-mixing scales better.</p>
    <img src="data:image/png;base64,{speed_img}" alt="Speed vs sequence length" />
  </div>

  <div class="chart">
    <h2>Quality (Validation Perplexity)</h2>
    <p>Validation perplexity for each model on a small Simple English Wikipedia slice
    (random-init or trained, depending on checkpoints).</p>
    <img src="data:image/png;base64,{quality_img}" alt="Quality comparison" />
  </div>

  <p style="font-size: 0.9rem; color: #555;">
    Generated by <code>demo/generate_report.py</code>. To reproduce, run:
    <code>uv run python demo/generate_report.py</code>.
  </p>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an HTML H(AI)LP report (default H(AI)LP-only)."
    )
    parser.add_argument(
        "--baseline",
        action="store_true",
        help="Include Baseline GPT charts for comparison.",
    )
    args = parser.parse_args()

    device = DEFAULT_DEVICE
    print(f"Generating report (runs on: {DEVICE_NAME} / {device})")

    # Build configs/models used across benchmarks
    b_cfg = BaselineConfig(
        vocab_size=50_257,
        layers=6,
        attention_heads=8,
        hidden_dim=512,
        ffn_expansion=4,
        context_window=4096,
        dropout=0.0,
    )
    h_cfg = HAILPConfig(
        vocab_size=50_257,
        layers=12,
        hidden_dim=512,
        ffn_sharing_group_size=4,
        low_rank_dim=64,
        adapter_rank=32,
        dropout=0.0,
    )

    hailp = HAILPModel(h_cfg)

    # Memory: use helper from memory_profile
    seq_lens: list[int] = [64, 128, 256, 512, 1024]
    mem_hailp = benchmark_memory_vs_sequence_length(
        hailp,
        "H(AI)LP RWKV",
        sequence_lengths=seq_lens,
        device=device,
        is_recurrent=True,
    )

    fig1, ax1 = plt.subplots()
    if args.baseline:
        baseline = BaselineGPT(b_cfg)
        mem_baseline = benchmark_memory_vs_sequence_length(
            baseline,
            "Baseline GPT",
            sequence_lengths=seq_lens,
            device=device,
            is_recurrent=False,
        )
        ax1.plot(
            [p.seq_len for p in mem_baseline],
            [p.peak_ram_mb for p in mem_baseline],
            label="Baseline GPT",
            marker="o",
        )

    ax1.plot(
        [p.seq_len for p in mem_hailp],
        [p.peak_ram_mb for p in mem_hailp],
        label="H(AI)LP RWKV",
        marker="o",
    )
    ax1.set_xlabel("Sequence length")
    ax1.set_ylabel("Peak RAM delta (MB)")
    ax1.set_title("Memory vs sequence length")
    ax1.legend()
    mem_img = _fig_to_base64(fig1)

    # Speed benchmark
    speed_results = benchmark_speed_vs_sequence_length(
        HAILPModel(h_cfg),
        "H(AI)LP RWKV",
        seq_lens=seq_lens,
        batch_size=1,
        device=device,
        is_recurrent=True,
    )
    if args.baseline:
        speed_results += benchmark_speed_vs_sequence_length(
            BaselineGPT(b_cfg),
            "Baseline GPT",
            seq_lens=seq_lens,
            batch_size=1,
            device=device,
            is_recurrent=False,
        )

    fig2, ax2 = plt.subplots()
    for model_name in sorted({r["model"] for r in speed_results}):
        xs = [r["seq_len"] for r in speed_results if r["model"] == model_name]
        ys = [r["tokens_per_second"] for r in speed_results if r["model"] == model_name]
        ax2.plot(xs, ys, marker="o", label=model_name)
    ax2.set_xlabel("Sequence length")
    ax2.set_ylabel("Tokens per second")
    ax2.set_title("Speed vs sequence length")
    ax2.legend()
    speed_img = _fig_to_base64(fig2)

    # Quality benchmark (small, random-init or from checkpoints if present)
    q_hailp = benchmark_quality(
        "hailp",
        checkpoint_dir=Path("checkpoints") if Path("checkpoints").exists() else None,
        max_batches=50,
        val_batches=100,
        device=device,
    )

    q_baseline = None
    if args.baseline:
        try:
            q_baseline = benchmark_quality(
                "baseline",
                checkpoint_dir=Path("checkpoints") if Path("checkpoints").exists() else None,
                max_batches=50,
                val_batches=100,
                device=device,
            )
        except Exception:
            q_baseline = benchmark_quality(
                "baseline",
                checkpoint_dir=None,
                max_batches=10,
                val_batches=20,
                device=device,
            )

    fig3, ax3 = plt.subplots()
    if args.baseline and q_baseline is not None:
        models = ["Baseline GPT", "H(AI)LP RWKV"]
        ppl = [q_baseline["perplexity"], q_hailp["perplexity"]]
        ax3.bar(models, ppl, color=["#1f77b4", "#ff7f0e"])
    else:
        ax3.bar(["H(AI)LP RWKV"], [q_hailp["perplexity"]], color=["#ff7f0e"])

    ax3.set_ylabel("Validation perplexity")
    ax3.set_title("Quality (lower is better)")
    quality_img = _fig_to_base64(fig3)

    html = generate_report_html(mem_img, speed_img, quality_img)
    out_path = Path("comparison_report.html")
    out_path.write_text(html, encoding="utf-8")
    print(f"Wrote report to {out_path.resolve()}")


if __name__ == "__main__":
    main()

